Fixing the el6 and el7 installation scripts and updated the variable names from the deb installation script.
I still see this when I run the centos installation script, This is
something that might need changes to the rpm spec file in the
bwc-topology repo.

Error: Package: bwc-topology-1.0.0-2.x86_64 (StackStorm_enterprise)
           Requires: /home/ubuntu/virtualenvs/venv-system/bin/python
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest